services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memoire
      PGDATA: /var/lib/postgresql/data/dbdata 
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/dbdata

  db-test:
    image: postgres:latest
    container_name: my_postgres_test_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memoire_test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
volumes:
  postgres_data: