name: Backend Build on Main Env

# Trigger the workflow only on pushes to specific branches and when changes are made to the 'backend' directory
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub using Access Token
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 

    # Step 3: Build the Backend Docker image
    - name: Build backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app-dev:latest ./backend

    # Step 4: Push the Backend Docker image to Docker Hub
    - name: Push backend image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-app-dev:latest